"""Bid service: orchestrates the hot-path and cold-path bid flow (TDD §9, §6).

This module separates bidding business logic from the WebSocket controller
(``bid_handler.py``), keeping the handler thin and testable.
"""
import json
from decimal import Decimal
from time import time
from uuid import UUID

import structlog
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.auction import Auction
from app.models.wallet import Wallet
from app.observability.metrics import BID_LATENCY
from app.redis.client import RedisClient

logger = structlog.get_logger()


class BidService:
    """Orchestrates bid validation via the Redis Lua hot path and Celery cold path."""

    ANTI_SNIPE_MS: int = 60_000  # milliseconds

    def __init__(self, db: AsyncSession, redis: RedisClient) -> None:
        """Initialise with a database session and a connected Redis client.

        Args:
            db: Active :class:`sqlalchemy.ext.asyncio.AsyncSession`.
            redis: Singleton :class:`app.redis.client.RedisClient` instance.
        """
        self.db = db
        self.redis = redis

    async def ensure_auction_state(self, auction: Auction) -> None:
        """Seed the Redis auction state hash if it is missing.

        This is required the first time any user bids on an auction so the
        Lua script can read state atomically without hitting PostgreSQL.

        Args:
            auction: The ORM auction object (must have ``item`` loaded).
        """
        state = await self.redis.get_auction_state(str(auction.id))
        if not state:
            await self.redis.set_auction_state(str(auction.id), {
                "current_price": str(auction.current_price),
                "leader_id": str(auction.winning_bidder_id) if auction.winning_bidder_id else "",
                "end_time": str(int(auction.end_time.timestamp() * 1000)),
                "status": auction.status,
                "min_bid_increment": str(auction.item.min_bid_increment),
            })

    async def ensure_wallet_state(self, user_id: UUID) -> bool:
        """Seed the Redis wallet hash for *user_id* from PostgreSQL if absent.

        Args:
            user_id: The bidder's UUID.

        Returns:
            ``True`` if the wallet state is (now) present, ``False`` if the
            user has no wallet in PostgreSQL.
        """
        wallet_state = await self.redis.get_user_wallet(str(user_id))
        if wallet_state:
            return True

        result = await self.db.execute(select(Wallet).where(Wallet.user_id == user_id))
        wallet = result.scalar_one_or_none()
        if not wallet:
            return False

        await self.redis.init_user_wallet(
            str(user_id),
            balance=str(wallet.balance),
            held=str(wallet.held_balance),
        )
        return True

    async def execute_hot_path(
        self,
        auction_id: str,
        user_id: str,
        amount_str: str,
        client_bid_id: str,
        min_bid_increment: str,
    ) -> dict:
        """Execute the atomic Lua bid script (hot path, TDD §6.2).

        Args:
            auction_id: String UUID of the auction.
            user_id: String UUID of the bidder.
            amount_str: Bid amount as a decimal string (e.g. ``"150.00"``).
            client_bid_id: UUID v4 generated by the frontend for deduplication.
            min_bid_increment: Minimum increment as a decimal string.

        Returns:
            Parsed JSON dict returned by the Lua script, with keys ``status``,
            and conditionally ``reason``, ``new_price``, ``new_end_time``, ``seq``.
        """
        now_ms = int(time() * 1000)
        start = time()

        try:
            result = await self.redis.evalsha(
                "bid_script",
                [
                    self.redis.auction_state_key(auction_id),
                    self.redis.user_wallet_key(user_id),
                ],
                [
                    amount_str,
                    str(now_ms),
                    user_id,
                    client_bid_id,
                    min_bid_increment,
                    str(self.ANTI_SNIPE_MS),
                ],
            )
            result_data: dict = json.loads(result)
        except Exception as exc:
            logger.error("lua_bid_error", exc=str(exc), auction_id=auction_id, user_id=user_id)
            result_data = {"status": "rejected", "reason": "service_unavailable"}

        latency = time() - start
        BID_LATENCY.labels(status=result_data.get("status", "unknown")).observe(latency)
        return result_data

    async def check_rate_limit(self, user_id: str, now_ms: int) -> dict:
        """Check the per-user bid rate limit (token bucket Lua, TDD §6.1, §8.2).

        Args:
            user_id: String UUID of the user.
            now_ms: Current Unix timestamp in milliseconds.

        Returns:
            Dict with ``allowed`` (bool) and optionally ``retry_after_ms``.
        """
        rate_result = await self.redis.evalsha(
            "rate_limit",
            [f"rate_limit:{user_id}:bid"],
            ["3", "0.333", "1", str(now_ms)],  # burst 3, 1 per 3 s
        )
        return json.loads(rate_result)

    async def check_dedup(self, user_id: str, client_bid_id: str) -> bool:
        """Return True if *client_bid_id* is a duplicate (already seen within 60 s).

        Args:
            user_id: String UUID of the user.
            client_bid_id: UUID v4 generated by the frontend.
        """
        dedup_result = await self.redis.evalsha(
            "dedup",
            [f"dedup:user:{user_id}"],
            [client_bid_id, "60"],
        )
        return json.loads(dedup_result).get("is_duplicate", False)
